config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patient_cards
  resources :patients
  resources :doctors
  resources :specializations
  resources :departments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "root#index"
end

app/models/department.rb
class Department < ApplicationRecord
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    departments_query = DepartmentsQuery.new
    @departments = departments_query.search(params[:query]).sort(params[:sort_field], params[:sort_direction]).result.paginate(page: params[:page], per_page: 10)
  end


  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to department_url(@department), notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to department_url(@department), notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:name, :address, :founding_date)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<div class="style_for_pages card" id="<%= dom_id department %>">
  <p class="card-header">
    <strong>Name:</strong>
    <%= department.name %>
  </p>

  <p class="card-body">
    <strong>Address:</strong>
    <%= department.address %>
  </p>

  <p class="card-body">
    <strong>Founding date:</strong>
    <%= department.founding_date %>
  </p>

</div>

app/views/departments/_form.html.erb
<div class="style_for_pages">

  <%= form_with(model: department) do |form| %>
    <% if department.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

        <ul>
          <% department.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :address, style: "display: block" %>
      <%= form.text_field :address %>
    </div>

    <div>
      <%= form.label :founding_date, style: "display: block" %>
      <%= form.date_field :founding_date %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/departments/edit.html.erb
<h1>Editing department</h1>
<div class="style_for_pages">
  <%= render "form", department: @department %>

  <br>

  <div>
    <%= link_to "Show this department", @department %> |
    <%= link_to "Back to departments", departments_path %>
  </div>
</div>

app/views/departments/index.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<h1>Departments</h1>

<div class="style_for_pages">
<%= form_with(url: departments_path, method: :get) do |form| %>
  <%= form.text_field :query, placeholder: 'Search departments', :class=>"form-control me-2" %>
  <%= form.submit 'Search', :class=>"btn btn-primary" %>
<% end %>

<div class="style_for_pages card" id="departments">
  <% @departments.each do |department| %>
    <%= render department %>
    <p>
      <%= link_to "Show this department", department, :class=>"card-footer btn btn-primary" %>
    </p>
  <% end %>
</div>

<%= will_paginate @departments, :class=>"page-link" %>

<p>
  <%= link_to 'New department', new_department_path %>
</p>

<p>
  Sort by:
  <%= link_to 'Name (asc)', { sort_field: 'name', sort_direction: 'asc' } %>
  <%= link_to 'Name (desc)', { sort_field: 'name', sort_direction: 'desc' } %>
  <%= link_to 'Created at (asc)', { sort_field: 'created_at', sort_direction: 'asc' } %>
  <%= link_to 'Created at (desc)', { sort_field: 'created_at', sort_direction: 'desc' } %>
</p>
</div>

app/views/departments/new.html.erb
<h1>New department</h1>

<
<div class="style_for_pages">
  <%= render "form", department: @department %>

  <br>

  <div>
    <%= link_to "Back to departments", departments_path %>
  </div>
</div>

app/views/departments/show.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<p style="color: green"><%= notice %></p>

<%= render @department %>

<div class="style_for_pages">
  <%= link_to "Edit this department", edit_department_path(@department), :class=>"btn btn-primary" %> |
  <%= link_to "Back to departments", departments_path, :class=>"btn btn-dark" %>

  <%= button_to "Destroy this department", @department, method: :delete, :class=>"btn btn-danger" %>
</div>