config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patient_cards
  resources :patients
  resources :doctors
  resources :specializations
  resources :departments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "root#index"
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :department
  belongs_to :specialization
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_doctor, only: %i[ show edit update destroy ]

  # GET /doctors or /doctors.json
  def index
    doctors_query = DoctorsQuery.new
    @doctors = doctors_query.search(params[:query]).sort(params[:sort_field], params[:sort_direction]).result.paginate(page: params[:page], per_page: 10)
  end

  # GET /doctors/1 or /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors or /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully created." }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1 or /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully updated." }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1 or /doctors/1.json
  def destroy
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url, notice: "Doctor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:name, :department_id, :specialization_id)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_doctor.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<div id="<%= dom_id doctor %>" class="style_for_pages card">
  <p class="card-header">
    <strong>Name:</strong>
    <%= doctor.name %>
  </p>

  <p class="card-body">
    <strong>Department:</strong>
    <%= doctor.department_id %>
  </p>

  <p class="card-body">
    <strong>Specialization:</strong>
    <%= doctor.specialization_id %>
  </p>

</div>

app/views/doctors/_form.html.erb
<div class="style_for_pages">

  <%= form_with(model: doctor) do |form| %>
    <% if doctor.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

        <ul>
          <% doctor.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :department_id, style: "display: block" %>
      <%= form.text_field :department_id %>
    </div>

    <div>
      <%= form.label :specialization_id, style: "display: block" %>
      <%= form.text_field :specialization_id %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<div class="style_for_pages">
  <%= render "form", doctor: @doctor %>

  <br>

  <div>
    <%= link_to "Show this doctor", @doctor %> |
    <%= link_to "Back to doctors", doctors_path %>
  </div>
</div>

app/views/doctors/index.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<p style="color: green"><%= notice %></p>

<h1>Doctors</h1>

<div class="style_for_pages">
<%= form_with(url: doctors_path, method: :get) do |form| %>
  <%= form.text_field :query, placeholder: 'Search doctors', :class=>"form-control me-2" %>
  <%= form.submit 'Search', :class=>"btn btn-primary" %>
<% end %>
<div id="doctors" class="style_for_pages card">
  <% @doctors.each do |doctor| %>
    <%= render doctor%>
    <p>
      <%= link_to "Show this doctor", doctor, :class=>"card-footer btn btn-primary" %>
    </p>
  <% end %>

  <%= will_paginate @doctors, :class=>"page-link" %>
</div>

<%= link_to "New doctor", new_doctor_path %>

<p>
  Sort by:
  <%= link_to 'Name (asc)', { sort_field: 'name', sort_direction: 'asc' } %>
  <%= link_to 'Name (desc)', { sort_field: 'name', sort_direction: 'desc' } %>
  <%= link_to 'Created at (asc)', { sort_field: 'created_at', sort_direction: 'asc' } %>
  <%= link_to 'Created at (desc)', { sort_field: 'created_at', sort_direction: 'desc' } %>
</p>

</div>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<div class="style_for_pages">
  <%= render "form", doctor: @doctor %>

  <br>

  <div>
    <%= link_to "Back to doctors", doctors_path %>
  </div>

</div>

app/views/doctors/show.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<p style="color: green"><%= notice %></p>

<div class="style_for_pages">
  <%= render @doctor %>

  <div>
    <%= link_to "Edit this doctor", edit_doctor_path(@doctor), :class=>"btn btn-primary" %> |
    <%= link_to "Back to doctors", doctors_path, :class=>"btn btn-dark" %>

    <%= button_to "Destroy this doctor", @doctor, method: :delete, :class=>"btn btn-danger" %>
  </div>
</div>